### ISSUE TITLE
Student Workshop Signup Page

### ISSUE THREAD

**Issue by ibehreini** [ibehreini/edgedashboard#3]
Create a page where students can sign up for workshops
- Workshop / Month selection [drop down]
- Transportation selection [drop down]
-Will attend yes/no
-Submit button
-Capture data values for future implementations

**Comment by htgiddings** [comment]
Came up with a design for the following pages:
- Workshop list
- Event list
- Event/Workshop detail page
- Signup Page

Thinking about the possibility of user settings, which would require an extra page.
